### ISSUE TITLE
What is recall.npy

### ISSUE THREAD

**Issue by ChrisLee63** [sjtuzq/person_search_gcn#4]
Hi, thanks for your great work.
![image](https://user-images.githubusercontent.com/39628662/69404444-42e73600-0d38-11ea-956f-2337a00a2c40.png)
The code run failed due to missing `recall.npy`
Could you help me? I will be grateful.

**Comment by sjtuzq** [comment]
Sorry for making such a mistake, I updated it just now.

**Comment by kjlee18** [comment]
> Sorry for making such a mistake, I updated it just now.

I tried just now, but it doesn't work.
